name: DynamicSpells
version: '${project.version}'
main: me.berrycraft.dynamicspells.DynamicSpells
api-version: '1.21'
commands:
  cast:
    description: Casts a spell
    usage: /cast <spell> <level>
    permission: dynamicspells.cast
  spellbook:
    description: Gives a spellbook
    usage: /spellbook <spell_name> <level>
    permission: dynamicspells.spellbook
  rotate:
    description: Rotates the currently copied structure 90 degrees clockwise
    usage: /rotate
    permission: dynamicspells.rotate