name: berry-economy
version: '${project.version}'
main: me.berrycraft.berryeconomy.Berry
api-version: '1.21.5'
depend: [NBTAPI]
commands:
  exchange:
    usage: /exchange
    description: exchange berries
  auction:
    usage: /auction
    description: open the auction house gui
  gamble:
    usage: /gamble
    description: purchase lootboxes
  berry:
    description: Manage all custom BerryCraft admin commands
    usage: /berry <give|table> <args>
    permission: berry-economy.admin